name: Feature request
description: Proposer une amélioration
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problème ou besoin
      description: Quel cas d'usage souhaitez-vous couvrir ?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
      description: Comment imagineriez-vous la fonctionnalité ?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Composant concerné
      options:
        - App macOS
        - Extension Raycast
        - Les deux
    validations:
      required: true
